### ISSUE TITLE
 Enhance the Team Page Card Design

### ISSUE THREAD

**Issue by Harsh-git98** [EDC-IIEST/Basic-Website#21]
**Description:**

Improve the design of the team member cards on the team page to enhance visual appeal and user experience.

**Task:**
1. Review the current design of the team member cards.
2. Implement improvements such as:
   - Updated card layout (e.g., larger images, better spacing).
   - Improved typography (e.g., font sizes, weights).
   - Consistent color schemes that align with the overall website design.
   - Hover effects to provide interactivity.
3. Ensure the cards are responsive and maintain a good layout on mobile devices.

**Comment by thanhloc03** [comment]
Can you assign this task to me?

**Comment by iamdhruvsaini** [comment]
@Harsh-git98 can i work on this task under hacktoberfest ?
