### ISSUE TITLE
Reduce Width of Navigation Bar for Improved UI

### ISSUE THREAD

**Issue by Harsh-git98** [EDC-IIEST/Basic-Website#22]
**Description:**

Enhance the user interface by reducing the width of the navigation bar to create a more balanced layout.

**Task:**
1. Review the current navigation bar design and its width.
2. Implement changes to reduce the width, ensuring it aligns with the overall aesthetic of the website.
3. Ensure the navigation items are still clearly visible and accessible after the width adjustment.

**Comment by ChampGupta** [comment]
@Harsh-git98 I would like to work on this repo under hactoberfest-accepted. Please assign me this issue. Also website is not deployed please deploy it and share the link if possible.
