### ISSUE TITLE
[Bug] : Social media icon not working properly on clicking

### ISSUE THREAD

**Issue by a-sksingh113** [EDC-IIEST/Basic-Website#32]
Description:
On Clicking INSTAGRAM ICON it is redirected to LINKEDIN page and on Clicking LINKEDIN it is redirected to INSTAGRAM.

how to reach the problem:
1-> go to instagram icon and click.

https://github.com/user-attachments/assets/36899ca8-b57b-4f89-a6aa-bf7eadc0cb5a

**Comment by a-sksingh113** [comment]
please review my pull request

**Comment by Harsh-git98** [comment]
Issue Resolved.
